# Program Information

## School Psychology Faculty

**Dr. Ryan Farmer**, Clinical Assistant Professor\
MA/EdS Program Director\
Director of the Psychological Services Center\
Rm. 126c\
901-678-2313 \| [r.farmer\@memphis.edu](mailto:r.farmer@memphis.edu){.email}\
Interests: Assessment practices in school psychology; the generation, adoption, and maintenance of low value and evidence-based practices in school psychology; and meta-scientific issues (e.g., ethics & philosophy of practice) in school psychology.
\
\
**Dr. Randy Floyd**, Professor\
Department Chair\
Rm. 332\
901-678-4846 \| [rgfloyd\@memphis.edu](mailto:rgfloyd@memphis.edu){.email}\
Ph.D. 1999, Indiana State University.\
Interests: Psychoeducational assessment, theories of intelligence, and academic achievement. Additionally, Dr. Floyd is interested in the study of school psychology's scientific literature.
\
\
**Dr. Beth Meisinger**, Professor \
Doctoral Program Director of Clinical Training\
Rm. 338\
901-678-3435 \| [bmsinger\@memphis.edu](mailto:bmsinger@memphis.edu){.email}\
Ph.D. 2006, University of Georgia\
Interests: Academic and behavioral interventions, consultation, school mental health
\
\
**Dr. Michelle Washington**, Assistant Professor \
Rm. 306 \| [mlwshng5\@memphis.edu](mailto:mlwshng5@memphis.edu){.email}\
Ph.D. 2022, Georgia State University\
Interests: Impact of diversification on the field of school psychology, including disproportionality, culturally competent service delivery, school psychology practice in urban settings, and the influence of racial-ethnic matching/incongruence on service delivery and student outcomes.
\
\
**Dr. Emily Srisarajivakul**, Assistant Professor \
Rm. 310 \| [emily.srisarajivakul\@memphis.edu](mailto:emily.srisarajivakul@memphis.edu){.email}\
Ph.D. 2021, Georgia State University\
Interests: School climate and safety, cultural humility, applications of positive psychological interventions in schools, and consultation with educators to promote equitable outcome

<small>*Last updated: `r format(file.info("sppc.Rmd")$mtime, "%B %d, %Y")`*</small>

